// Comprehensive Repair Skills Data
const comprehensiveTasks = [
  // Core Foundation Skills
  {id: 'C001', category: 'Core', subcategory: 'Safety', name: 'ESD compliance & safe workspace setup', tier: '1 - Foundation', target_mins: 5, qc_checks: 3, tools: 'ESD mat, strap, grounding tester', risk: 'Low', description: 'Set up ESD workstation, verify ground, inspect tools for safety.', team: 'Both'},
  {id: 'C002', category: 'Core', subcategory: 'Safety', name: 'Tool calibration & maintenance', tier: '1 - Foundation', target_mins: 15, qc_checks: 5, tools: 'Calibration kit, multimeter', risk: 'Low', description: 'Check torque drivers, multimeters, hot air stations, soldering irons.', team: 'Both'},
  {id: 'C003', category: 'Core', subcategory: 'Safety', name: 'Workspace organization & cleanup', tier: '1 - Foundation', target_mins: 10, qc_checks: 3, tools: 'Cleaning supplies, organization tools', risk: 'Low', description: 'Organize tools, clean workspace, dispose waste properly, maintain 5S.', team: 'Both'},
  {id: 'C004', category: 'Core', subcategory: 'Safety', name: 'Chemical safety & handling', tier: '1 - Foundation', target_mins: 20, qc_checks: 5, tools: 'Safety data sheets, PPE', risk: 'Medium', description: 'Handle isopropyl alcohol, flux, adhesives safely with proper PPE.', team: 'Both'},
  {id: 'C005', category: 'Core', subcategory: 'Safety', name: 'Battery disposal & recycling', tier: '1 - Foundation', target_mins: 10, qc_checks: 3, tools: 'Safety container, gloves, fire extinguisher', risk: 'Medium', description: 'Properly dispose of damaged batteries, follow environmental regulations.', team: 'Both'},
  {id: 'C006', category: 'Core', subcategory: 'Safety', name: 'Mains isolation & capacitor discharge', tier: '2 - Advanced', target_mins: 20, qc_checks: 8, tools: 'Insulated tools, HV resistor, LOTO kit', risk: 'High', description: 'LOTO procedures, verify isolation, discharge HV capacitors safely.', team: 'Both'},
  
  // Diagnostic & Testing
  {id: 'D001', category: 'Diagnostic', subcategory: 'Software', name: 'Device diagnostics & testing', tier: '1 - Foundation', target_mins: 20, qc_checks: 5, tools: 'Diagnostic software, cables, test fixtures', risk: 'Low', description: 'Run comprehensive device diagnostics, identify issues.', team: 'Both'},
  {id: 'D002', category: 'Diagnostic', subcategory: 'Hardware', name: 'Component testing & verification', tier: '2 - Advanced', target_mins: 30, qc_checks: 8, tools: 'Multimeter, oscilloscope, logic analyzer', risk: 'Low', description: 'Test individual components, verify functionality, measure signals.', team: 'Both'},
  {id: 'D003', category: 'Diagnostic', subcategory: 'Performance', name: 'Performance benchmarking', tier: '2 - Advanced', target_mins: 25, qc_checks: 6, tools: 'Benchmark software, thermal camera, power meter', risk: 'Low', description: 'Run performance tests, check thermal behavior, power consumption.', team: 'Both'},
  {id: 'D004', category: 'Diagnostic', subcategory: 'Network', name: 'Network connectivity testing', tier: '1 - Foundation', target_mins: 15, qc_checks: 4, tools: 'Network tools, cables, test devices', risk: 'Low', description: 'Test WiFi, Bluetooth, cellular connectivity, network protocols.', team: 'Both'},
  {id: 'D005', category: 'Diagnostic', subcategory: 'Audio', name: 'Audio system testing', tier: '1 - Foundation', target_mins: 15, qc_checks: 4, tools: 'Audio test equipment, test files', risk: 'Low', description: 'Test speakers, microphones, audio quality, noise levels.', team: 'Both'},
  {id: 'D006', category: 'Diagnostic', subcategory: 'Display', name: 'Display quality testing', tier: '1 - Foundation', target_mins: 20, qc_checks: 5, tools: 'Color calibration tools, test patterns', risk: 'Low', description: 'Test display brightness, color accuracy, touch sensitivity, dead pixels.', team: 'Both'},
  
  // iPhone Repairs
  {id: 'P001', category: 'iPhone', subcategory: 'Battery', name: 'iPhone Battery replacement (standard)', tier: '2 - Advanced', target_mins: 25, qc_checks: 8, tools: 'Diagnostic battery, torque driver, adhesive', risk: 'Low', description: 'Replace iPhone battery, calibrate, test charging cycles.', team: 'Both'},
  {id: 'P002', category: 'iPhone', subcategory: 'Battery', name: 'iPhone Battery replacement (with errors)', tier: '3 - Expert', target_mins: 40, qc_checks: 12, tools: 'Programmer, diagnostic tools, calibration kit', risk: 'Medium', description: 'Clear battery error codes, calibrate new battery, restore functionality.', team: 'Both'},
  {id: 'P003', category: 'iPhone', subcategory: 'Display', name: 'iPhone Display replacement + True Tone', tier: '2 - Advanced', target_mins: 35, qc_checks: 10, tools: 'Programmer, True Tone calibrator, dust control', risk: 'Low', description: 'Replace display, restore True Tone, maintain dust-free environment.', team: 'Both'},
  {id: 'P004', category: 'iPhone', subcategory: 'Display', name: 'iPhone Back glass replacement', tier: '3 - Expert', target_mins: 60, qc_checks: 12, tools: 'Heat mat, cards, laser, precision tools', risk: 'Medium', description: 'Remove back glass safely, replace with new unit, maintain water resistance.', team: 'Both'},
  {id: 'P005', category: 'iPhone', subcategory: 'Camera', name: 'iPhone Camera replacement', tier: '2 - Advanced', target_mins: 30, qc_checks: 8, tools: 'Torque driver, camera tester, alignment tools', risk: 'Medium', description: 'Replace camera module, test all functions, ensure proper alignment.', team: 'Both'},
  {id: 'P006', category: 'iPhone', subcategory: 'Camera', name: 'iPhone Camera lens replacement', tier: '2 - Advanced', target_mins: 20, qc_checks: 6, tools: 'Heat mat, precision tools, lens cleaner', risk: 'Low', description: 'Replace cracked camera lens, clean internal components.', team: 'Both'},
  {id: 'P007', category: 'iPhone', subcategory: 'Charging', name: 'iPhone Lightning port replacement', tier: '2 - Advanced', target_mins: 35, qc_checks: 8, tools: 'Heat mat, precision tools, port cleaner', risk: 'Medium', description: 'Replace Lightning port assembly, test charging and data transfer.', team: 'Both'},
  {id: 'P008', category: 'iPhone', subcategory: 'Audio', name: 'iPhone Speaker replacement', tier: '2 - Advanced', target_mins: 25, qc_checks: 6, tools: 'Torque driver, audio tester', risk: 'Low', description: 'Replace speaker assembly, test audio quality and volume.', team: 'Both'},
  {id: 'P009', category: 'iPhone', subcategory: 'Audio', name: 'iPhone Microphone replacement', tier: '2 - Advanced', target_mins: 20, qc_checks: 6, tools: 'Torque driver, microphone tester', risk: 'Low', description: 'Replace microphone assembly, test recording quality.', team: 'Both'},
  {id: 'P010', category: 'iPhone', subcategory: 'Logic Board', name: 'iPhone Logic Board repair', tier: '4 - Master', target_mins: 180, qc_checks: 25, tools: 'Microscope, hot air station, BGA tools', risk: 'High', description: 'Component-level repair, power management, data recovery.', team: 'Both'},
  {id: 'P011', category: 'iPhone', subcategory: 'Logic Board', name: 'iPhone Water damage repair', tier: '4 - Master', target_mins: 120, qc_checks: 20, tools: 'Ultrasonic cleaner, microscope, corrosion treatment', risk: 'High', description: 'Clean corrosion, replace damaged components, restore functionality.', team: 'Both'},
  {id: 'P012', category: 'iPhone', subcategory: 'Wireless', name: 'iPhone Wireless charging repair', tier: '2 - Advanced', target_mins: 30, qc_checks: 8, tools: 'Wireless charger tester, precision tools', risk: 'Medium', description: 'Repair wireless charging coil, test charging efficiency.', team: 'Both'},
  
  // Samsung Galaxy Repairs
  {id: 'P021', category: 'Samsung Galaxy', subcategory: 'Display', name: 'Samsung AMOLED + FP calibration', tier: '3 - Expert', target_mins: 45, qc_checks: 12, tools: 'Service app, fingerprint jig, calibration tools', risk: 'Medium', description: 'Replace AMOLED display, run fingerprint calibration, test touch.', team: 'Both'},
  {id: 'P022', category: 'Samsung Galaxy', subcategory: 'Display', name: 'Samsung Back glass replacement', tier: '3 - Expert', target_mins: 50, qc_checks: 10, tools: 'Heat mat, precision tools, laser', risk: 'Medium', description: 'Remove back glass, replace with new unit, maintain design integrity.', team: 'Both'},
  {id: 'P023', category: 'Samsung Galaxy', subcategory: 'Battery', name: 'Samsung Battery replacement', tier: '2 - Advanced', target_mins: 35, qc_checks: 8, tools: 'Heat mat, precision tools, battery tester', risk: 'Medium', description: 'Remove back glass, replace battery, test charging cycles.', team: 'Both'},
  {id: 'P024', category: 'Samsung Galaxy', subcategory: 'Charging', name: 'Samsung USB-C port replacement', tier: '2 - Advanced', target_mins: 30, qc_checks: 6, tools: 'Heat mat, precision tools, port cleaner', risk: 'Low', description: 'Replace USB-C port assembly, test charging and data transfer.', team: 'Both'},
  {id: 'P025', category: 'Samsung Galaxy', subcategory: 'Camera', name: 'Samsung Camera replacement', tier: '2 - Advanced', target_mins: 35, qc_checks: 8, tools: 'Torque driver, camera tester, alignment tools', risk: 'Medium', description: 'Replace camera module, test all functions, ensure proper alignment.', team: 'Both'},
  {id: 'P026', category: 'Samsung Galaxy', subcategory: 'Audio', name: 'Samsung Speaker replacement', tier: '2 - Advanced', target_mins: 25, qc_checks: 6, tools: 'Torque driver, audio tester', risk: 'Low', description: 'Replace speaker assembly, test audio quality and volume.', team: 'Both'},
  {id: 'P027', category: 'Samsung Galaxy', subcategory: 'Logic Board', name: 'Samsung Logic Board repair', tier: '4 - Master', target_mins: 150, qc_checks: 20, tools: 'Microscope, hot air station, BGA tools', risk: 'High', description: 'Component-level repair, power management, data recovery.', team: 'Both'},
  {id: 'P028', category: 'Samsung Galaxy', subcategory: 'Wireless', name: 'Samsung Wireless charging repair', tier: '2 - Advanced', target_mins: 30, qc_checks: 8, tools: 'Wireless charger tester, precision tools', risk: 'Medium', description: 'Repair wireless charging coil, test charging efficiency.', team: 'Both'},
  
  // iPad Repairs
  {id: 'T001', category: 'iPad', subcategory: 'Battery', name: 'iPad Battery replacement', tier: '3 - Expert', target_mins: 60, qc_checks: 15, tools: 'Isopropyl alcohol, precision tools, adhesive', risk: 'Medium', description: 'Remove screen safely, lift battery cells, reseal with proper adhesive.', team: 'Both'},
  {id: 'T002', category: 'iPad', subcategory: 'Display', name: 'iPad Display replacement', tier: '3 - Expert', target_mins: 75, qc_checks: 18, tools: 'Heat mat, suction cups, precision tools', risk: 'Medium', description: 'Remove display assembly, replace with new unit, test all functions.', team: 'Both'},
  {id: 'T003', category: 'iPad', subcategory: 'Home Button', name: 'iPad Home Button replacement', tier: '2 - Advanced', target_mins: 40, qc_checks: 10, tools: 'Torque driver, adhesive, Touch ID tester', risk: 'Low', description: 'Replace home button, test Touch ID functionality.', team: 'Both'},
  {id: 'T004', category: 'iPad', subcategory: 'Charging', name: 'iPad Lightning port replacement', tier: '2 - Advanced', target_mins: 45, qc_checks: 10, tools: 'Heat mat, precision tools, port cleaner', risk: 'Medium', description: 'Replace Lightning port assembly, test charging and data transfer.', team: 'Both'},
  {id: 'T005', category: 'iPad', subcategory: 'Audio', name: 'iPad Speaker replacement', tier: '2 - Advanced', target_mins: 30, qc_checks: 8, tools: 'Torque driver, audio tester', risk: 'Low', description: 'Replace speaker assembly, test audio quality and volume.', team: 'Both'},
  {id: 'T006', category: 'iPad', subcategory: 'Logic Board', name: 'iPad Logic Board repair', tier: '4 - Master', target_mins: 180, qc_checks: 25, tools: 'Microscope, hot air station, BGA tools', risk: 'High', description: 'Component-level repair, power management, data recovery.', team: 'Both'},
  
  // MacBook Repairs
  {id: 'L001', category: 'MacBook', subcategory: 'Keyboard', name: 'MacBook Keyboard replacement', tier: '3 - Expert', target_mins: 150, qc_checks: 20, tools: 'Rivet kit, precision drivers, backlight tester', risk: 'Medium', description: 'Split top case, transfer rivets and screws, test backlight functionality.', team: 'Both'},
  {id: 'L002', category: 'MacBook', subcategory: 'Display', name: 'MacBook Display replacement', tier: '3 - Expert', target_mins: 120, qc_checks: 15, tools: 'Torque driver, adhesive, display tester', risk: 'Medium', description: 'Replace display assembly, test all functions and color accuracy.', team: 'Both'},
  {id: 'L003', category: 'MacBook', subcategory: 'Logic Board', name: 'MacBook Logic Board repair', tier: '4 - Master', target_mins: 240, qc_checks: 30, tools: 'Microscope, hot air station, BGA rework station', risk: 'High', description: 'Component-level repair, power management, data recovery.', team: 'Both'},
  {id: 'L004', category: 'MacBook', subcategory: 'Power', name: 'MacBook MagSafe port replacement', tier: '2 - Advanced', target_mins: 75, qc_checks: 12, tools: 'Torque driver, precision tools, port tester', risk: 'Medium', description: 'Replace MagSafe port assembly, test charging functionality.', team: 'Both'},
  {id: 'L005', category: 'MacBook', subcategory: 'Storage', name: 'MacBook SSD replacement', tier: '2 - Advanced', target_mins: 60, qc_checks: 10, tools: 'Torque driver, precision tools, data migration tools', risk: 'Low', description: 'Replace SSD, restore from backup, test performance.', team: 'Both'},
  {id: 'L006', category: 'MacBook', subcategory: 'Audio', name: 'MacBook Speaker replacement', tier: '2 - Advanced', target_mins: 50, qc_checks: 10, tools: 'Torque driver, audio tester', risk: 'Low', description: 'Replace speaker assembly, test audio quality and volume.', team: 'Both'},
  {id: 'L007', category: 'MacBook', subcategory: 'Trackpad', name: 'MacBook Trackpad replacement', tier: '3 - Expert', target_mins: 90, qc_checks: 15, tools: 'Precision tools, trackpad tester', risk: 'Medium', description: 'Replace trackpad assembly, test multi-touch functionality.', team: 'Both'},
  
  // Gaming Console Repairs
  {id: 'G001', category: 'PlayStation', subcategory: 'HDMI', name: 'PlayStation HDMI port replacement', tier: '4 - Master', target_mins: 120, qc_checks: 20, tools: 'Hot air station, microscope, BGA tools', risk: 'High', description: 'Hot air + iron work, pad repair, retimer chip replacement.', team: 'Both'},
  {id: 'G002', category: 'PlayStation', subcategory: 'Power', name: 'PlayStation Power supply replacement', tier: '2 - Advanced', target_mins: 45, qc_checks: 10, tools: 'Torque driver, power tester', risk: 'Medium', description: 'Replace power supply unit, test power delivery.', team: 'Both'},
  {id: 'G003', category: 'PlayStation', subcategory: 'Storage', name: 'PlayStation HDD/SSD replacement', tier: '1 - Foundation', target_mins: 30, qc_checks: 6, tools: 'Torque driver, data migration tools', risk: 'Low', description: 'Replace storage drive, reinstall OS, migrate data.', team: 'Both'},
  {id: 'G004', category: 'PlayStation', subcategory: 'Optical', name: 'PlayStation Disc drive replacement', tier: '3 - Expert', target_mins: 90, qc_checks: 15, tools: 'Precision tools, disc drive tester', risk: 'Medium', description: 'Replace optical disc drive, test disc reading functionality.', team: 'Both'},
  
  {id: 'G011', category: 'Xbox', subcategory: 'HDMI', name: 'Xbox HDMI port replacement', tier: '4 - Master', target_mins: 120, qc_checks: 20, tools: 'Hot air station, microscope, BGA tools', risk: 'High', description: 'Hot air + iron work, pad repair, retimer chip replacement.', team: 'Both'},
  {id: 'G012', category: 'Xbox', subcategory: 'Power', name: 'Xbox Power supply replacement', tier: '2 - Advanced', target_mins: 45, qc_checks: 10, tools: 'Torque driver, power tester', risk: 'Medium', description: 'Replace power supply unit, test power delivery.', team: 'Both'},
  {id: 'G013', category: 'Xbox', subcategory: 'Storage', name: 'Xbox HDD/SSD replacement', tier: '1 - Foundation', target_mins: 30, qc_checks: 6, tools: 'Torque driver, data migration tools', risk: 'Low', description: 'Replace storage drive, reinstall OS, migrate data.', team: 'Both'},
  {id: 'G014', category: 'Xbox', subcategory: 'Optical', name: 'Xbox Disc drive replacement', tier: '3 - Expert', target_mins: 90, qc_checks: 15, tools: 'Precision tools, disc drive tester', risk: 'Medium', description: 'Replace optical disc drive, test disc reading functionality.', team: 'Both'},
  
  {id: 'G021', category: 'Nintendo Switch', subcategory: 'Display', name: 'Nintendo Switch Display replacement', tier: '3 - Expert', target_mins: 60, qc_checks: 12, tools: 'Heat mat, precision tools, display tester', risk: 'Medium', description: 'Replace Switch display, test touch sensitivity and color accuracy.', team: 'Both'},
  {id: 'G022', category: 'Nintendo Switch', subcategory: 'Joy-Con', name: 'Nintendo Switch Joy-Con repair', tier: '2 - Advanced', target_mins: 45, qc_checks: 10, tools: 'Torque driver, precision tools, analog stick tester', risk: 'Low', description: 'Repair Joy-Con drift, replace buttons, test all functions.', team: 'Both'},
  {id: 'G023', category: 'Nintendo Switch', subcategory: 'Charging', name: 'Nintendo Switch USB-C port replacement', tier: '3 - Expert', target_mins: 75, qc_checks: 15, tools: 'Hot air station, precision tools, port tester', risk: 'Medium', description: 'Replace USB-C port, test charging and data transfer.', team: 'Both'},
  {id: 'G024', category: 'Nintendo Switch', subcategory: 'Logic Board', name: 'Nintendo Switch Logic Board repair', tier: '4 - Master', target_mins: 150, qc_checks: 20, tools: 'Microscope, hot air station, BGA tools', risk: 'High', description: 'Component-level repair, power management, data recovery.', team: 'Both'},
  
  // Additional Device Types
  {id: 'W001', category: 'Apple Watch', subcategory: 'Display', name: 'Apple Watch Display replacement', tier: '3 - Expert', target_mins: 60, qc_checks: 15, tools: 'Heat mat, precision tools, display tester', risk: 'Medium', description: 'Replace Apple Watch display, test touch sensitivity and force touch.', team: 'Both'},
  {id: 'W002', category: 'Apple Watch', subcategory: 'Battery', name: 'Apple Watch Battery replacement', tier: '3 - Expert', target_mins: 45, qc_checks: 12, tools: 'Heat mat, precision tools, battery tester', risk: 'Medium', description: 'Replace Apple Watch battery, test charging and battery health.', team: 'Both'},
  {id: 'W003', category: 'Apple Watch', subcategory: 'Crown', name: 'Apple Watch Digital Crown replacement', tier: '2 - Advanced', target_mins: 30, qc_checks: 8, tools: 'Torque driver, precision tools, crown tester', risk: 'Low', description: 'Replace Digital Crown, test rotation and button functionality.', team: 'Both'},
  
  {id: 'A001', category: 'AirPods', subcategory: 'Battery', name: 'AirPods Battery replacement', tier: '3 - Expert', target_mins: 45, qc_checks: 12, tools: 'Heat mat, precision tools, battery tester', risk: 'Medium', description: 'Replace AirPods battery, test charging and audio quality.', team: 'Both'},
  {id: 'A002', category: 'AirPods', subcategory: 'Audio', name: 'AirPods Speaker replacement', tier: '2 - Advanced', target_mins: 30, qc_checks: 8, tools: 'Precision tools, audio tester', risk: 'Low', description: 'Replace AirPods speaker, test audio quality and noise cancellation.', team: 'Both'},
  {id: 'A003', category: 'AirPods', subcategory: 'Charging', name: 'AirPods Charging case repair', tier: '2 - Advanced', target_mins: 25, qc_checks: 6, tools: 'Heat mat, precision tools, charging tester', risk: 'Low', description: 'Repair AirPods charging case, test charging functionality.', team: 'Both'},
  
  {id: 'H001', category: 'Headphones', subcategory: 'Audio', name: 'Headphone Speaker replacement', tier: '2 - Advanced', target_mins: 30, qc_checks: 8, tools: 'Precision tools, audio tester', risk: 'Low', description: 'Replace headphone speakers, test audio quality and balance.', team: 'Both'},
  {id: 'H002', category: 'Headphones', subcategory: 'Cable', name: 'Headphone Cable replacement', tier: '1 - Foundation', target_mins: 20, qc_checks: 5, tools: 'Soldering iron, cable tester', risk: 'Low', description: 'Replace headphone cable, test audio and microphone functionality.', team: 'Both'},
  {id: 'H003', category: 'Headphones', subcategory: 'Wireless', name: 'Wireless Headphone repair', tier: '3 - Expert', target_mins: 60, qc_checks: 15, tools: 'Precision tools, wireless tester', risk: 'Medium', description: 'Repair wireless headphone connectivity, test Bluetooth functionality.', team: 'Both'},
  
  {id: 'R001', category: 'Data Recovery', subcategory: 'Software', name: 'Data recovery from damaged devices', tier: '3 - Expert', target_mins: 120, qc_checks: 20, tools: 'Data recovery software, specialized cables', risk: 'Medium', description: 'Recover data from damaged devices, test data integrity.', team: 'Both'},
  {id: 'R002', category: 'Data Recovery', subcategory: 'Hardware', name: 'Logic board data recovery', tier: '4 - Master', target_mins: 180, qc_checks: 25, tools: 'Microscope, hot air station, data recovery tools', risk: 'High', description: 'Component-level data recovery, repair damaged storage chips.', team: 'Both'},
  {id: 'R003', category: 'Data Recovery', subcategory: 'Water Damage', name: 'Water damaged device data recovery', tier: '4 - Master', target_mins: 150, qc_checks: 20, tools: 'Ultrasonic cleaner, corrosion treatment, data recovery tools', risk: 'High', description: 'Clean corrosion, recover data from water damaged devices.', team: 'Both'},
  
  {id: 'Q001', category: 'Quality Control', subcategory: 'Testing', name: 'Device quality control testing', tier: '2 - Advanced', target_mins: 30, qc_checks: 10, tools: 'QC test suite, measurement tools', risk: 'Low', description: 'Comprehensive device testing, verify all functions work correctly.', team: 'Both'},
  {id: 'Q002', category: 'Quality Control', subcategory: 'Calibration', name: 'Device calibration & tuning', tier: '3 - Expert', target_mins: 45, qc_checks: 12, tools: 'Calibration tools, measurement equipment', risk: 'Medium', description: 'Calibrate device sensors, optimize performance, fine-tune settings.', team: 'Both'},
  {id: 'Q003', category: 'Quality Control', subcategory: 'Documentation', name: 'Repair documentation & reporting', tier: '1 - Foundation', target_mins: 15, qc_checks: 5, tools: 'Documentation system, camera', risk: 'Low', description: 'Document repair process, take photos, create detailed reports.', team: 'Both'}
];
